name: bm3
channels:
  - https://conda.graylab.jhu.edu
  - oddt
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - alabaster=0.7.12=py36_0
  - attrs=19.3.0=py_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - blosc=1.15.0=hd408876_0
  - bokeh=2.0.2=py36_0
  - ca-certificates=2020.1.1=0
  - cachecontrol=0.12.5=py36_0
  - certifi=2020.4.5.1=py36_0
  - cffi=1.14.0=py36he30daa8_1
  - chardet=3.0.4=py36_1003
  - click=7.1.2=py_0
  - cloudpickle=1.4.1=py_0
  - contextvars=2.4=py_0
  - cryptography=2.9.2=py36h1ba5d50_0
  - cycler=0.10.0=py36_0
  - cytoolz=0.10.1=py36h7b6447c_0
  - dask=2.17.2=py_0
  - dask-core=2.17.2=py_0
  - dask-jobqueue=0.7.0=py_0
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.17.0=py36_0
  - docutils=0.16=py36_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fsspec=0.7.4=py_0
  - glib=2.63.1=h3eb4bd4_1
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - heapdict=1.0.1=py_0
  - icu=58.2=he6710b0_3
  - idna=2.9=py_1
  - imagesize=1.2.0=py_0
  - immutables=0.11=py36h7b6447c_0
  - importlib-metadata=1.6.0=py36_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2020.1=217
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.13.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.0=py36_0
  - jinja2=2.11.2=py_0
  - joblib=0.15.1=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py36_0
  - kiwisolver=1.2.0=py36hfd86e86_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - locket=0.2.0=py36_1
  - lockfile=0.12.2=py36_0
  - lz4-c=1.9.2=he6710b0_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - msgpack-python=1.0.0=py36hfd86e86_1
  - natsort=7.0.1=py_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.6=py_0
  - ncurses=6.2=he6710b0_1
  - nose=1.3.7=py36_2
  - notebook=6.0.3=py36_0
  - numpy=1.18.1=py36h4f9e942_0
  - numpy-base=1.18.1=py36hde5b4d6_1
  - numpydoc=0.9.2=py_0
  - oddt=0.7=py_0
  - olefile=0.46=py36_0
  - openssl=1.1.1g=h7b6447c_0
  - packaging=20.3=py_0
  - pandas=1.0.3=py36h0573a6f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.7.0=py_0
  - partd=1.1.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.1.2=py36hb39fc2d_0
  - pip=20.0.2=py36_3
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - psutil=5.7.0=py36h7b6447c_0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrosetta=2020.23+release.0d6f90a=py36_0
  - pyrsistent=0.16.0=py36h7b6447c_0
  - pysocks=1.7.1=py36_0
  - python=3.6.10=h7579374_2
  - python-blosc=1.7.0=py36h7b6447c_0
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py36h7b6447c_0
  - pyzmq=18.1.1=py36he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.4=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py36_0
  - scikit-bio=0.5.2=py36h3010b51_0
  - scikit-learn=0.22.1=py36hd81dba3_0
  - scipy=1.4.1=py36h0b6359f_0
  - send2trash=1.5.0=py36_0
  - setuptools=47.1.1=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=py_0
  - snappy=1.1.7=hbae5bb6_3
  - snowballstemmer=2.0.0=py_0
  - sortedcontainers=2.1.0=py36_0
  - sphinx=3.0.4=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.31.1=h62c20be_1
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py36h7b6447c_1
  - tqdm=4.46.0=py_0
  - traitlets=4.3.3=py36_0
  - typing_extensions=3.7.4.1=py36_0
  - urllib3=1.25.8=py36_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py36_1
  - wheel=0.34.2=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
prefix: /home/james/anaconda3/envs/bm3

